diff --git a/Makefile b/Makefile
index 4833ec1..bc4c36b 100644
--- a/Makefile
+++ b/Makefile
@@ -1,10 +1,15 @@
-PREFIX = ${HOME}/.blodwen
+INSTALL ?= install
+MKDIR   ?= $(INSTALL) -d
+DESTDIR ?=
+PREFIX  ?= ${HOME}/.blodwen
+BINDIR  ?= $(PREFIX)/bin
+
 export BLODWEN_PATH = ${CURDIR}/prelude/build:${CURDIR}/base/build
 export BLODWEN_DATA = ${CURDIR}/support
 
 .PHONY: ttimp blodwen prelude test base clean lib_clean
 
-all: ttimp blodwen prelude base test
+all: ttimp blodwen prelude base
 
 ttimp:
 	idris --build ttimp.ipkg
@@ -15,7 +20,7 @@ blodwen: src/BlodwenPaths.idr
 src/BlodwenPaths.idr:
 	echo 'module BlodwenPaths; export bprefix : String; bprefix = "${PREFIX}"' > src/BlodwenPaths.idr
 
-prelude:
+prelude: blodwen
 	make -C prelude BLODWEN=../blodwen
 
 base: prelude
@@ -34,19 +39,17 @@ lib_clean:
 	make -C prelude clean
 	make -C base clean
 
-test:
+test: base
 	idris --build test.ipkg
 	make -C tests
 
 install:
-	mkdir -p ${PREFIX}/bin
-	mkdir -p ${PREFIX}/blodwen/support/chez
-	mkdir -p ${PREFIX}/blodwen/support/chicken
-	mkdir -p ${PREFIX}/blodwen/support/racket
-	make -C prelude install BLODWEN=../blodwen
-	make -C base install BLODWEN=../blodwen
-
-	install blodwen ${PREFIX}/bin
-	install support/chez/* ${PREFIX}/blodwen/support/chez
-	install support/chicken/* ${PREFIX}/blodwen/support/chicken
-	install support/racket/* ${PREFIX}/blodwen/support/racket
+	$(MKDIR) ${DESTDIR}${BINDIR}
+	$(MKDIR) ${DESTDIR}${PREFIX}/blodwen/support/chez
+	$(MKDIR) ${DESTDIR}${PREFIX}/blodwen/support/chicken
+	$(MKDIR) ${DESTDIR}${PREFIX}/blodwen/support/racket
+
+	$(INSTALL) blodwen ${DESTDIR}${BINDIR}
+	$(INSTALL) support/chez/* ${DESTDIR}${PREFIX}/blodwen/support/chez
+	$(INSTALL) support/chicken/* ${DESTDIR}${PREFIX}/blodwen/support/chicken
+	$(INSTALL) support/racket/* ${DESTDIR}${PREFIX}/blodwen/support/racket
